CREATE TABLE USERTYPE (
USERTYPEID INT PRIMARY KEY, 
TITLE VARCHAR2(10));

CREATE TABLE US3R (
USERID INT PRIMARY KEY,
FIRSTNAME VARCHAR2(10), 
LASTNAME VARCHAR2(10),
USERNAME VARCHAR2(10), 
PASSW0RD VARCHAR2(16),
FOREIGN KEY (USERTYPEID) REFERENCES USERTYPE(USERTYPEID));

CREATE TABLE CONDITIONTYPE (
CONDITIONTYPEID INT PRIMARY KEY,
CONDITIONTYPENAME VARCHAR2(10));

CREATE TABLE OWNERSHIPTYPE (
OWNERSHIPTYPEID INT PRIMARY KEY, 
OWNERSHIPTYPENAME VARCHAR2(10));

CREATE TABLE CAR(
CARID INT PRIMARY KEY,
CARYEAR VARCHAR2(4), 
MAKE VARCHAR2(20),
CARMODEL VARCHAR2(20),
COLOR VARCHAR2(10),
FOREIGN KEY (CONDITIONID) REFERENCES CONDITIONTYPE(CONDITIONTYPEID), --MAKE CONDITIONTYPE TABLE
FOREIGN KEY (OWNERSHIPTYPEID) REFERENCES OWNERSHIPTYPE(OWNERSHIPTYPEID),
FOREIGN KEY (USERID) REFERENCES US3R(USERID));

CREATE TABLE OFFER(
OFFERID INT PRIMARY KEY, 
FOREIGN KEY (CARID) REFERENCES CAR(CARDID),
FOREIGN KEY (USERID) REFERENCES USER(USERID),
OFFERPRICE NUMBER(6));

--SEQUENCES
CREATE SEQUENCE USERTYPESEQ;
CREATE SEQUENCE US3RSEQ;
CREATE SEQUENCE CONDITIONTYPESEQ;
CREATE SEQUENCE OWNERSHIPTYPESEQ;
CREATE SEQUENCE CARSEQ;
CREATE SEQUENCE OFFERSEQ;

--INSERT PROCEDURE
CREATE OR REPLACE PROCEDURE INSERTUSER(NAME IN VARCHAR2)
AS
BEGIN
    INSERT INTO US3R VALUES(US3RSEQ.NEXTVAL, NAME);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERTCAR(NAME IN VARCHAR2)
AS
BEGIN
    INSERT INTO CAR VALUES(CARSEQ.NEXTVAL, NAME);
COMMIT;
END;
/

--INSERT STATEMENTS FOR USERTYPE -- DONE
INSERT INTO USERTYPE VALUES('ADMIN');  --1
INSERT INTO USERTYPE VALUES('EMPLOYEE'); --2
INSERT INTO USERTYPE VALUES('CUSTOMER'); --3

--INSERT STATMENTS FOR US3R
INSERT INTO US3R VALUES('ADMIN', 'ISTRATOR', 'ADMIN', 'PASSW0RD123', 1);

--INSERT STATEMENTS FOR CONDITIONTYPE -- DONE
INSERT INTO CONDITIONTYPE VALUES('EXCELLENT');
INSERT INTO CONDITIONTYPE VALUES('GOOD');
INSERT INTO CONDITIONTYPE VALUES('FAIR');
INSERT INTO CONDITIONTYPE VALUES('POOR');

--INSERT STATEMENTS FOR OWNERSHIPTYPE -- DONE
INSERT INTO OWNERSHIPTYPE VALUES('FORSALE');
INSERT INTO OWNERSHIPTYPE VALUES('OWNED');

--INSERT STATMENTS FOR CAR
INSERT INTO CAR VALUES('1990', 'FORD', 'FIESTA', 'GREEN', 4, 1);
INSERT INTO CAR VALUES('1991', 'Toyota', 'Camry', 'BLACK', 1, 1);
INSERT INTO CAR VALUES('1992', 'Chevrolet', 'Corvette', 'BLUE', 2, 1);
INSERT INTO CAR VALUES('1993', 'Porsche', 'Cayman', 'Red', 3, 1);
INSERT INTO CAR VALUES('1994', 'Nissan', 'Pathfinder', 'Green', 4, 1);
INSERT INTO CAR VALUES('1995', 'Ford', 'Windstar', 'Purple', 2, 1);
INSERT INTO CAR VALUES('1996', 'Chevrolet', 'Tahoe', 'White', 2, 1);
INSERT INTO CAR VALUES('1997', 'Toyota', 'Sequoia', 'Tan', 1, 1);
INSERT INTO CAR VALUES('1998', 'Nissan', 'Altima', 'Orange', 4, 1);
INSERT INTO CAR VALUES('1999', 'Ford', 'Mustang', 'Yellow', 3, 1);


--INSERT STATMENTS OF OFFER

